version: "0.5"

# API server uses UDS (-U flag) to avoid port conflict with Caddy on 8080

processes:
  cloudflared:
    command: xplat sync-cf tunnel ${CADDY_PORT}
    log_location: ${DATA_DIR}/tunnel.log

  tunnel-setup:
    command: xplat task authelia:tunnel:setup --dir ${ROOT_DIR}
    depends_on:
      cloudflared:
        condition: process_started
    availability:
      restart: "no"
      exit_on_end: false

  caddy:
    command: ${CADDY} run --config ${DATA_DIR}/Caddyfile
    depends_on:
      tunnel-setup:
        condition: process_completed_successfully

  authelia:
    command: >-
      ${AUTH_BINARY}
      --config ${AUTH_CONFIG}
      --config ${AUTH_FLOWS_DIR}/${AUTH_FLOW}.yml
      --config ${DATA_DIR}/config.session.yml
    depends_on:
      tunnel-setup:
        condition: process_completed_successfully
