version: "0.5"

# Disable process-compose API server to avoid conflicting with Caddy on 8080
disable_server: true

processes:
  cloudflared:
    command: >-
      ${CLOUDFLARED} tunnel
      --url http://127.0.0.1:${CADDY_PORT}
    log_location: ${DATA_DIR}/tunnel.log
    readiness_probe:
      exec:
        command: grep -q 'trycloudflare\.com' ${DATA_DIR}/tunnel.log 2>/dev/null
      initial_delay_seconds: 2
      period_seconds: 1
      failure_threshold: 30

  tunnel-setup:
    command: ${ROOT_DIR}/scripts/tunnel-setup.sh
    depends_on:
      cloudflared:
        condition: process_healthy
    availability:
      restart: "no"
      exit_on_end: false

  caddy:
    command: ${CADDY} run --config ${DATA_DIR}/Caddyfile
    depends_on:
      tunnel-setup:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: lsof -ti :${CADDY_PORT} >/dev/null 2>&1
      initial_delay_seconds: 1
      period_seconds: 1
      failure_threshold: 10

  authelia:
    command: >-
      ${AUTH_BINARY}
      --config ${AUTH_CONFIG}
      --config ${AUTH_FLOWS_DIR}/${AUTH_FLOW}.yml
      --config ${DATA_DIR}/config.session.yml
    depends_on:
      tunnel-setup:
        condition: process_completed_successfully
    readiness_probe:
      exec:
        command: curl -sk https://127.0.0.1:${AUTH_PORT}/api/health >/dev/null 2>&1
      initial_delay_seconds: 1
      period_seconds: 1
      failure_threshold: 10
