version: "3"

vars:
  BIN_DIR: "{{.ROOT_DIR}}/.bin"
  SRC_DIR: "{{.ROOT_DIR}}/.src"
  DATA_DIR: "{{.ROOT_DIR}}/.data"

includes:
  authelia:
    taskfile: ./systems/authelia/Taskfile.yml
    dir: ./systems/authelia

tasks: {}
