version: "3"

vars:
  AUTHELIA_VERSION: "4.39.15"
  AUTHELIA_SWAGGER_VERSION: "5.30.2"
  AUTHELIA_PORT: "9091"
  CADDY_VERSION: "2.9.1"
  CADDY_PORT: "8080"
  # OS/ARCH use Task built-in {{OS}} and {{ARCH}} (work on all platforms)
  HOST_EXT: '{{if eq OS "windows"}}.exe{{end}}'
  AUTHELIA_BINARY: "{{.BIN_DIR}}/authelia{{.HOST_EXT}}"
  AUTHELIA_SRC: "{{.SRC_DIR}}/authelia"
  AUTHELIA_DATA: "{{.DATA_DIR}}/authelia"
  AUTHELIA_GH_REPO: "joeblew999/plat-auth"
  AUTHELIA_GH_TAG: "authelia-v{{.AUTHELIA_VERSION}}-{{OS}}-{{ARCH}}"
  AUTHELIA_BIN_ASSET: "authelia-{{OS}}-{{ARCH}}"
  AUTHELIA_CONFIG: "{{.ROOT_DIR}}/systems/authelia/config.yml"
  AUTHELIA_FLOWS_DIR: "{{.ROOT_DIR}}/systems/authelia/flows"
  # Caddy uses "mac" not "darwin" in release asset names
  CADDY_OS: '{{if eq OS "darwin"}}mac{{else}}{{OS}}{{end}}'
  CADDY_ARCHIVE_EXT: '{{if eq OS "windows"}}zip{{else}}tar.gz{{end}}'
  CADDY_BINARY: "{{.BIN_DIR}}/caddy{{.HOST_EXT}}"
  CADDYFILE_TEMPLATE: "{{.ROOT_DIR}}/systems/authelia/Caddyfile.template"

tasks:
  debug:
    desc: Print all Authelia vars
    silent: true
    cmds:
      - |
        echo "OS:                  {{OS}}"
        echo "ARCH:                {{ARCH}}"
        echo "HOST_EXT:            {{.HOST_EXT}}"
        echo "AUTHELIA_VERSION:    {{.AUTHELIA_VERSION}}"
        echo "AUTHELIA_PORT:       {{.AUTHELIA_PORT}}"
        echo "AUTHELIA_BINARY:     {{.AUTHELIA_BINARY}}"
        echo "AUTHELIA_SRC:        {{.AUTHELIA_SRC}}"
        echo "AUTHELIA_DATA:       {{.AUTHELIA_DATA}}"
        echo "AUTHELIA_GH_REPO:    {{.AUTHELIA_GH_REPO}}"
        echo "AUTHELIA_GH_TAG:     {{.AUTHELIA_GH_TAG}}"
        echo "AUTHELIA_BIN_ASSET:  {{.AUTHELIA_BIN_ASSET}}"
        echo "AUTHELIA_CONFIG:     {{.AUTHELIA_CONFIG}}"
        echo "AUTHELIA_FLOWS_DIR:  {{.AUTHELIA_FLOWS_DIR}}"
        echo "CADDY_VERSION:       {{.CADDY_VERSION}}"
        echo "CADDY_BINARY:        {{.CADDY_BINARY}}"
        echo "CADDY_OS:            {{.CADDY_OS}}"
        echo "BIN_DIR:             {{.BIN_DIR}}"
        echo "SRC_DIR:             {{.SRC_DIR}}"
        echo "DATA_DIR:            {{.DATA_DIR}}"

  src:clone:
    desc: Clone the Authelia source
    cmds:
      - xplat os mkdir -p {{.SRC_DIR}}
      - xplat os git clone https://github.com/authelia/authelia.git {{.AUTHELIA_SRC}} v{{.AUTHELIA_VERSION}}
    status:
      - xplat os exists {{.AUTHELIA_SRC}}/.git

  src:deps:
    desc: Install Authelia build dependencies
    deps:
      - src:clone
    dir: ".src/authelia"
    env:
      GOWORK: "off"
    cmds:
      - go mod download all
      - task: src:deps:web

  src:deps:web:
    internal: true
    dir: ".src/authelia/web"
    cmds:
      - bun install

  src:build:
    desc: Build Authelia from source
    deps:
      - src:deps
    dir: ".src/authelia"
    env:
      GOWORK: "off"
    cmds:
      - task: src:build:web
      - xplat os fetch --extract https://github.com/swagger-api/swagger-ui/archive/v{{.AUTHELIA_SWAGGER_VERSION}}.tar.gz --output {{.AUTHELIA_SRC}}/internal/server/public_html/api --strip 2 --include "*/dist/*"
      - xplat os cp {{.AUTHELIA_SRC}}/api {{.AUTHELIA_SRC}}/internal/server/public_html/api -r
      - CGO_ENABLED=1 go build -ldflags "-s -w" -trimpath -o {{.AUTHELIA_BINARY}} ./cmd/authelia

  src:build:web:
    internal: true
    dir: ".src/authelia/web"
    cmds:
      - bun run build

  bin:upload:
    desc: Upload the Authelia binary to GitHub Releases
    preconditions:
      - sh: xplat os exists {{.AUTHELIA_BINARY}}
        msg: "Binary not found at {{.AUTHELIA_BINARY}}. Build it first with src:build."
    cmds:
      - gh release create "{{.AUTHELIA_GH_TAG}}" --repo {{.AUTHELIA_GH_REPO}} --title "Authelia {{.AUTHELIA_VERSION}} ({{OS}}/{{ARCH}})" --notes "Built from authelia v{{.AUTHELIA_VERSION}}" 2>/dev/null || true
      - cp {{.AUTHELIA_BINARY}} {{.BIN_DIR}}/{{.AUTHELIA_BIN_ASSET}}
      - gh release upload "{{.AUTHELIA_GH_TAG}}" {{.BIN_DIR}}/{{.AUTHELIA_BIN_ASSET}} --repo {{.AUTHELIA_GH_REPO}} --clobber
      - rm {{.BIN_DIR}}/{{.AUTHELIA_BIN_ASSET}}

  bin:download:
    desc: Download the Authelia binary from GitHub Releases
    cmds:
      - xplat os mkdir -p {{.BIN_DIR}}
      - gh release download "{{.AUTHELIA_GH_TAG}}" --repo {{.AUTHELIA_GH_REPO}} --pattern "{{.AUTHELIA_BIN_ASSET}}" --output {{.AUTHELIA_BINARY}} --clobber
      - chmod +x {{.AUTHELIA_BINARY}} 2>/dev/null || true
    status:
      - xplat os exists {{.AUTHELIA_BINARY}}

  reset:
    desc: Reset Authelia data (deletes DB and notifications)
    cmds:
      - task: stop
      - xplat os rm -rf {{.AUTHELIA_DATA}}

  stop:
    desc: Stop Authelia and Caddy
    cmds:
      - xplat process down -U 2>/dev/null || true

  caddy:download:
    desc: Download Caddy binary from GitHub Releases
    cmds:
      - xplat os mkdir -p {{.BIN_DIR}}
      - xplat os fetch --extract https://github.com/caddyserver/caddy/releases/download/v{{.CADDY_VERSION}}/caddy_{{.CADDY_VERSION}}_{{.CADDY_OS}}_{{.HOST_ARCH}}.{{.CADDY_ARCHIVE_EXT}} --output {{.BIN_DIR}} --include "caddy*"
      - chmod +x {{.CADDY_BINARY}} 2>/dev/null || true
    status:
      - xplat os exists {{.CADDY_BINARY}}

  tls:generate:
    internal: true
    cmds:
      - xplat os mkdir -p {{.AUTHELIA_DATA}}/tls
      - >-
        openssl req -x509 -nodes -newkey rsa:2048
        -keyout {{.AUTHELIA_DATA}}/tls/key.pem
        -out {{.AUTHELIA_DATA}}/tls/cert.pem
        -days 3650
        -subj "/CN=127.0.0.1"
        -addext "subjectAltName=IP:127.0.0.1"
    status:
      - xplat os exists {{.AUTHELIA_DATA}}/tls/cert.pem

  start:
    desc: Start Authelia locally
    dir: "systems/authelia"
    dotenv:
      - .env
    deps:
      - bin:download
      - tls:generate
    env:
      AUTHELIA_STORAGE_LOCAL_PATH: "{{.AUTHELIA_DATA}}/db.sqlite3"
      AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH: "{{.ROOT_DIR}}/systems/authelia/users_database.yml"
      AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME: "{{.AUTHELIA_DATA}}/notification.txt"
      AUTHELIA_SERVER_TLS_CERTIFICATE: "{{.AUTHELIA_DATA}}/tls/cert.pem"
      AUTHELIA_SERVER_TLS_KEY: "{{.AUTHELIA_DATA}}/tls/key.pem"
    cmds:
      - xplat os mkdir -p {{.AUTHELIA_DATA}}
      - xplat os cp .env.example .env 2>/dev/null || true
      - |
        echo ""
        echo "  Authelia      https://127.0.0.1:{{.AUTHELIA_PORT}}"
        echo "  Swagger UI    https://127.0.0.1:{{.AUTHELIA_PORT}}/api/"
        echo ""
        echo "  Login: admin / admin"
        echo ""
      - >-
        {{.AUTHELIA_BINARY}}
        --config {{.AUTHELIA_CONFIG}}
        --config {{.AUTHELIA_FLOWS_DIR}}/2fa.yml
        {{.CLI_ARGS}}

  tunnel:
    desc: Start Authelia via Cloudflare Tunnel with 2FA (default)
    cmds:
      - task: tunnel:run
        vars:
          AUTH_FLOW: 2fa

  tunnel:1fa:
    desc: Start Authelia via Cloudflare Tunnel — password only (no 2FA)
    cmds:
      - task: tunnel:run
        vars:
          AUTH_FLOW: 1fa

  tunnel:setup:
    desc: Extract tunnel URL and generate configs (called by process-compose)
    silent: true
    env:
      AUTH_PORT: "{{.AUTHELIA_PORT}}"
    cmds:
      - |
        echo "  Waiting for Cloudflare Tunnel URL..."
        TUNNEL_URL=""
        i=0
        while [ -z "$TUNNEL_URL" ] && [ "$i" -lt 60 ]; do
          TUNNEL_URL=$(xplat os jq -r 'select(.message | test("https://[a-z0-9-]+\\.trycloudflare\\.com")) | .message | match("https://[a-z0-9-]+\\.trycloudflare\\.com").string' "{{.AUTHELIA_DATA}}/tunnel.log" 2>/dev/null | { read -r line; echo "$line"; }) || true
          if [ -z "$TUNNEL_URL" ]; then sleep 1; fi
          i=$((i + 1))
        done
        if [ -z "$TUNNEL_URL" ]; then
          echo "  ERROR: Failed to get tunnel URL after 60s"
          exit 1
        fi
        TUNNEL_DOMAIN=${TUNNEL_URL#https://}
        export TUNNEL_URL TUNNEL_DOMAIN AUTH_PORT
        xplat os envsubst "{{.ROOT_DIR}}/systems/authelia/config.tunnel.yml.tmpl" -o "{{.AUTHELIA_DATA}}/config.session.yml"
        xplat os cp "{{.CADDYFILE_TEMPLATE}}" "{{.AUTHELIA_DATA}}/Caddyfile"
        echo ""
        echo "  Tunnel URL:  $TUNNEL_URL"
        echo "  Portal:      $TUNNEL_URL/authelia"
        echo "  Login:       admin / admin"
        echo ""

  tunnel:run:
    internal: true
    dir: "systems/authelia"
    dotenv:
      - .env
    deps:
      - bin:download
      - tls:generate
      - caddy:download
    env:
      CADDY: "{{.CADDY_BINARY}}"
      CADDY_PORT: "{{.CADDY_PORT}}"
      CADDYFILE_TEMPLATE: "{{.CADDYFILE_TEMPLATE}}"
      AUTH_BINARY: "{{.AUTHELIA_BINARY}}"
      AUTH_CONFIG: "{{.AUTHELIA_CONFIG}}"
      AUTH_PORT: "{{.AUTHELIA_PORT}}"
      AUTH_FLOW: "{{.AUTH_FLOW}}"
      AUTH_FLOWS_DIR: "{{.AUTHELIA_FLOWS_DIR}}"
      DATA_DIR: "{{.AUTHELIA_DATA}}"
      ROOT_DIR: "{{.ROOT_DIR}}"
      AUTHELIA_STORAGE_LOCAL_PATH: "{{.AUTHELIA_DATA}}/db.sqlite3"
      AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH: "{{.ROOT_DIR}}/systems/authelia/users_database.yml"
      AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME: "{{.AUTHELIA_DATA}}/notification.txt"
      AUTHELIA_SERVER_TLS_CERTIFICATE: "{{.AUTHELIA_DATA}}/tls/cert.pem"
      AUTHELIA_SERVER_TLS_KEY: "{{.AUTHELIA_DATA}}/tls/key.pem"
    cmds:
      - task: stop
      - xplat os mkdir -p {{.AUTHELIA_DATA}}
      - xplat os cp .env.example .env 2>/dev/null || true
      - xplat os rm -f {{.AUTHELIA_DATA}}/tunnel.log
      - >-
        xplat process up -t=false -U -f {{.ROOT_DIR}}/process-compose.yml
