version: "3"

vars:
  AUTHELIA_VERSION: "4.39.15"
  AUTHELIA_SWAGGER_VERSION: "5.30.2"
  AUTHELIA_PORT: "9091"
  AUTHELIA_OS:
    sh: go env GOOS
  AUTHELIA_ARCH:
    sh: go env GOARCH
  AUTHELIA_EXT:
    sh: go env GOEXE
  AUTHELIA_BINARY: "{{.BIN_DIR}}/authelia{{.AUTHELIA_EXT}}"
  AUTHELIA_SRC: "{{.SRC_DIR}}/authelia"
  AUTHELIA_DATA: "{{.DATA_DIR}}/authelia"
  AUTHELIA_GH_REPO: "joeblew999/plat-auth"
  AUTHELIA_GH_TAG: "authelia-v{{.AUTHELIA_VERSION}}-{{.AUTHELIA_OS}}-{{.AUTHELIA_ARCH}}"
  AUTHELIA_BIN_ASSET: "authelia-{{.AUTHELIA_OS}}-{{.AUTHELIA_ARCH}}"
  AUTHELIA_CONFIG: "{{.ROOT_DIR}}/systems/authelia/config.yml"
  AUTHELIA_FLOWS_DIR: "{{.ROOT_DIR}}/systems/authelia/flows"

tasks:
  debug:
    desc: Print all Authelia vars
    silent: true
    cmds:
      - |
        echo "AUTHELIA_VERSION:    {{.AUTHELIA_VERSION}}"
        echo "AUTHELIA_PORT:       {{.AUTHELIA_PORT}}"
        echo "AUTHELIA_OS:         {{.AUTHELIA_OS}}"
        echo "AUTHELIA_ARCH:       {{.AUTHELIA_ARCH}}"
        echo "AUTHELIA_EXT:        {{.AUTHELIA_EXT}}"
        echo "AUTHELIA_BINARY:     {{.AUTHELIA_BINARY}}"
        echo "AUTHELIA_SRC:        {{.AUTHELIA_SRC}}"
        echo "AUTHELIA_DATA:       {{.AUTHELIA_DATA}}"
        echo "AUTHELIA_GH_REPO:    {{.AUTHELIA_GH_REPO}}"
        echo "AUTHELIA_GH_TAG:     {{.AUTHELIA_GH_TAG}}"
        echo "AUTHELIA_BIN_ASSET:  {{.AUTHELIA_BIN_ASSET}}"
        echo "AUTHELIA_CONFIG:     {{.AUTHELIA_CONFIG}}"
        echo "AUTHELIA_FLOWS_DIR:  {{.AUTHELIA_FLOWS_DIR}}"
        echo "BIN_DIR:             {{.BIN_DIR}}"
        echo "SRC_DIR:             {{.SRC_DIR}}"
        echo "DATA_DIR:            {{.DATA_DIR}}"

  src:clone:
    desc: Clone the Authelia source
    cmds:
      - xplat os mkdir -p {{.SRC_DIR}}
      - xplat os git clone https://github.com/authelia/authelia.git {{.AUTHELIA_SRC}} v{{.AUTHELIA_VERSION}}
    status:
      - test -d {{.AUTHELIA_SRC}}/.git

  src:deps:
    desc: Install Authelia build dependencies
    deps:
      - src:clone
    dir: ".src/authelia"
    env:
      GOWORK: "off"
    cmds:
      - go mod download all
      - task: src:deps:web

  src:deps:web:
    internal: true
    dir: ".src/authelia/web"
    cmds:
      - bun install

  src:build:
    desc: Build Authelia from source
    deps:
      - src:deps
    dir: ".src/authelia"
    env:
      GOWORK: "off"
    cmds:
      - task: src:build:web
      - xplat os fetch --extract https://github.com/swagger-api/swagger-ui/archive/v{{.AUTHELIA_SWAGGER_VERSION}}.tar.gz --output {{.AUTHELIA_SRC}}/internal/server/public_html/api --strip 2 --include "*/dist/*"
      - xplat os cp {{.AUTHELIA_SRC}}/api {{.AUTHELIA_SRC}}/internal/server/public_html/api -r
      - CGO_ENABLED=1 go build -ldflags "-s -w" -trimpath -o {{.AUTHELIA_BINARY}} ./cmd/authelia

  src:build:web:
    internal: true
    dir: ".src/authelia/web"
    cmds:
      - bun run build

  bin:upload:
    desc: Upload the Authelia binary to GitHub Releases
    preconditions:
      - sh: test -f {{.AUTHELIA_BINARY}}
        msg: "Binary not found at {{.AUTHELIA_BINARY}}. Build it first with src:build."
    cmds:
      - gh release create "{{.AUTHELIA_GH_TAG}}" --repo {{.AUTHELIA_GH_REPO}} --title "Authelia {{.AUTHELIA_VERSION}} ({{.AUTHELIA_OS}}/{{.AUTHELIA_ARCH}})" --notes "Built from authelia v{{.AUTHELIA_VERSION}}" 2>/dev/null || true
      - gh release upload "{{.AUTHELIA_GH_TAG}}" {{.AUTHELIA_BINARY}}#{{.AUTHELIA_BIN_ASSET}} --repo {{.AUTHELIA_GH_REPO}} --clobber

  bin:download:
    desc: Download the Authelia binary from GitHub Releases
    cmds:
      - xplat os mkdir -p {{.BIN_DIR}}
      - gh release download "{{.AUTHELIA_GH_TAG}}" --repo {{.AUTHELIA_GH_REPO}} --pattern "{{.AUTHELIA_BIN_ASSET}}" --output {{.AUTHELIA_BINARY}} --clobber
      - chmod +x {{.AUTHELIA_BINARY}} 2>/dev/null || true
    status:
      - test -f {{.AUTHELIA_BINARY}}

  reset:
    desc: Reset Authelia data (deletes DB and notifications)
    cmds:
      - task: stop
      - xplat os rm -rf {{.AUTHELIA_DATA}}

  stop:
    desc: Stop Authelia
    cmds:
      - lsof -ti :{{.AUTHELIA_PORT}} | xargs kill 2>/dev/null || true

  tls:generate:
    internal: true
    cmds:
      - xplat os mkdir -p {{.AUTHELIA_DATA}}/tls
      - >-
        openssl req -x509 -nodes -newkey rsa:2048
        -keyout {{.AUTHELIA_DATA}}/tls/key.pem
        -out {{.AUTHELIA_DATA}}/tls/cert.pem
        -days 3650
        -subj "/CN=127.0.0.1"
        -addext "subjectAltName=IP:127.0.0.1"
    status:
      - test -f {{.AUTHELIA_DATA}}/tls/cert.pem

  start:
    desc: Start Authelia locally
    dir: "systems/authelia"
    dotenv:
      - .env
    deps:
      - bin:download
      - tls:generate
    env:
      AUTHELIA_STORAGE_LOCAL_PATH: "{{.AUTHELIA_DATA}}/db.sqlite3"
      AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH: "{{.ROOT_DIR}}/systems/authelia/users_database.yml"
      AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME: "{{.AUTHELIA_DATA}}/notification.txt"
      AUTHELIA_SERVER_TLS_CERTIFICATE: "{{.AUTHELIA_DATA}}/tls/cert.pem"
      AUTHELIA_SERVER_TLS_KEY: "{{.AUTHELIA_DATA}}/tls/key.pem"
    cmds:
      - lsof -ti :{{.AUTHELIA_PORT}} | xargs kill 2>/dev/null || true
      - xplat os mkdir -p {{.AUTHELIA_DATA}}
      - xplat os cp .env.example .env 2>/dev/null || true
      - |
        echo ""
        echo "  Authelia      https://127.0.0.1:{{.AUTHELIA_PORT}}"
        echo "  Swagger UI    https://127.0.0.1:{{.AUTHELIA_PORT}}/api/"
        echo ""
        echo "  Login: admin / admin"
        echo ""
      - >-
        {{.AUTHELIA_BINARY}}
        --config {{.AUTHELIA_CONFIG}}
        --config {{.AUTHELIA_FLOWS_DIR}}/2fa.yml
        {{.CLI_ARGS}}

  tunnel:
    desc: Start Authelia via Cloudflare Tunnel with 2FA (default)
    cmds:
      - task: tunnel:run
        vars:
          AUTH_FLOW: 2fa

  tunnel:1fa:
    desc: Start Authelia via Cloudflare Tunnel — password only (no 2FA)
    cmds:
      - task: tunnel:run
        vars:
          AUTH_FLOW: 1fa

  tunnel:run:
    internal: true
    dir: "systems/authelia"
    dotenv:
      - .env
    env:
      AUTH_BINARY: "{{.AUTHELIA_BINARY}}"
      AUTH_CONFIG: "{{.AUTHELIA_CONFIG}}"
      AUTH_PORT: "{{.AUTHELIA_PORT}}"
      AUTH_FLOW: "{{.AUTH_FLOW}}"
      AUTH_FLOWS_DIR: "{{.AUTHELIA_FLOWS_DIR}}"
      DATA_DIR: "{{.AUTHELIA_DATA}}"
      AUTHELIA_STORAGE_LOCAL_PATH: "{{.AUTHELIA_DATA}}/db.sqlite3"
      AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH: "{{.ROOT_DIR}}/systems/authelia/users_database.yml"
      AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME: "{{.AUTHELIA_DATA}}/notification.txt"
    deps:
      - bin:download
    cmds:
      - xplat sync-cf check 2>/dev/null || xplat sync-cf install
      - task: stop
      - xplat os mkdir -p {{.AUTHELIA_DATA}}
      - xplat os cp .env.example .env 2>/dev/null || true
      - "{{.ROOT_DIR}}/scripts/tunnel.sh"
