version: "3"

vars:
  AUTHELIA_VERSION: "4.39.15"
  AUTHELIA_PORT: "9091"
  AUTHELIA_OS:
    sh: go env GOOS
  AUTHELIA_ARCH:
    sh: go env GOARCH
  AUTHELIA_EXT:
    sh: go env GOEXE
  AUTHELIA_BINARY: "{{.BIN_DIR}}/authelia{{.AUTHELIA_EXT}}"
  AUTHELIA_SRC: "{{.SRC_DIR}}/authelia"
  AUTHELIA_DATA: "{{.DATA_DIR}}/authelia"
  AUTHELIA_GH_REPO: "joeblew999/plat-auth"
  AUTHELIA_GH_TAG: "authelia-v{{.AUTHELIA_VERSION}}-{{.AUTHELIA_OS}}-{{.AUTHELIA_ARCH}}"
  AUTHELIA_BIN_ASSET: "authelia-{{.AUTHELIA_OS}}-{{.AUTHELIA_ARCH}}"
  AUTHELIA_CONFIG: "{{.ROOT_DIR}}/systems/authelia/config.yml"

tasks:
  debug:
    desc: Print all Authelia vars
    silent: true
    cmds:
      - |
        echo "AUTHELIA_VERSION:    {{.AUTHELIA_VERSION}}"
        echo "AUTHELIA_PORT:       {{.AUTHELIA_PORT}}"
        echo "AUTHELIA_OS:         {{.AUTHELIA_OS}}"
        echo "AUTHELIA_ARCH:       {{.AUTHELIA_ARCH}}"
        echo "AUTHELIA_EXT:        {{.AUTHELIA_EXT}}"
        echo "AUTHELIA_BINARY:     {{.AUTHELIA_BINARY}}"
        echo "AUTHELIA_SRC:        {{.AUTHELIA_SRC}}"
        echo "AUTHELIA_DATA:       {{.AUTHELIA_DATA}}"
        echo "AUTHELIA_GH_REPO:    {{.AUTHELIA_GH_REPO}}"
        echo "AUTHELIA_GH_TAG:     {{.AUTHELIA_GH_TAG}}"
        echo "AUTHELIA_BIN_ASSET:  {{.AUTHELIA_BIN_ASSET}}"
        echo "AUTHELIA_CONFIG:     {{.AUTHELIA_CONFIG}}"
        echo "BIN_DIR:             {{.BIN_DIR}}"
        echo "SRC_DIR:             {{.SRC_DIR}}"
        echo "DATA_DIR:            {{.DATA_DIR}}"

  src:clone:
    desc: Clone the Authelia source
    cmds:
      - mkdir -p {{.SRC_DIR}}
      - git clone --depth 1 --branch v{{.AUTHELIA_VERSION}} https://github.com/authelia/authelia.git {{.AUTHELIA_SRC}}
    status:
      - test -d {{.AUTHELIA_SRC}}/.git

  src:deps:
    desc: Install Authelia build dependencies
    dir: "{{.AUTHELIA_SRC}}"
    deps:
      - src:clone
    env:
      GOWORK: "off"
    cmds:
      - go mod download all
      - cd web && bun install

  src:build:
    desc: Build Authelia from source
    dir: "{{.AUTHELIA_SRC}}"
    deps:
      - src:deps
    env:
      GOWORK: "off"
    cmds:
      - cd web && bun run build
      - cp -r api internal/server/public_html/api
      - CGO_ENABLED=1 go build -ldflags "-s -w" -trimpath -o {{.AUTHELIA_BINARY}} ./cmd/authelia
      - chmod +x {{.AUTHELIA_BINARY}}

  bin:upload:
    desc: Upload the Authelia binary to GitHub Releases
    preconditions:
      - sh: test -f {{.AUTHELIA_BINARY}}
        msg: "Binary not found at {{.AUTHELIA_BINARY}}. Build it first with src:build."
    cmds:
      - gh release create "{{.AUTHELIA_GH_TAG}}" --repo {{.AUTHELIA_GH_REPO}} --title "Authelia {{.AUTHELIA_VERSION}} ({{.AUTHELIA_OS}}/{{.AUTHELIA_ARCH}})" --notes "Built from authelia v{{.AUTHELIA_VERSION}}" 2>/dev/null || true
      - gh release upload "{{.AUTHELIA_GH_TAG}}" {{.AUTHELIA_BINARY}}#{{.AUTHELIA_BIN_ASSET}} --repo {{.AUTHELIA_GH_REPO}} --clobber

  bin:download:
    desc: Download the Authelia binary from GitHub Releases
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - gh release download "{{.AUTHELIA_GH_TAG}}" --repo {{.AUTHELIA_GH_REPO}} --pattern "{{.AUTHELIA_BIN_ASSET}}" --output {{.AUTHELIA_BINARY}} --clobber
      - chmod +x {{.AUTHELIA_BINARY}}
    status:
      - test -f {{.AUTHELIA_BINARY}}

  stop:
    desc: Stop Authelia
    cmds:
      - lsof -ti :{{.AUTHELIA_PORT}} | xargs kill 2>/dev/null || true

  start:
    desc: Start Authelia
    dotenv:
      - .env
    deps:
      - bin:download
    env:
      AUTHELIA_STORAGE_LOCAL_PATH: "{{.AUTHELIA_DATA}}/db.sqlite3"
      AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH: "{{.ROOT_DIR}}/systems/authelia/users_database.yml"
      AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME: "{{.AUTHELIA_DATA}}/notification.txt"
    cmds:
      - lsof -ti :{{.AUTHELIA_PORT}} | xargs kill 2>/dev/null || true
      - mkdir -p {{.AUTHELIA_DATA}}
      - cp -n .env.example .env 2>/dev/null || true
      - |
        echo ""
        echo "  Authelia UI  http://127.0.0.1:{{.AUTHELIA_PORT}}"
        echo "  Authelia API http://127.0.0.1:{{.AUTHELIA_PORT}}/api/"
        echo ""
        echo "  Login: admin / admin"
        echo ""
      - "{{.AUTHELIA_BINARY}} --config {{.AUTHELIA_CONFIG}} {{.CLI_ARGS}}"
